### ISSUE TITLE
Retry on connection errors

### ISSUE THREAD

**Issue by pivnicek** [davidesner/keboola-adform-masterdata-extractor#2]
The extractor will fail on connection errors like `Authentization error. Http Response code:504 - Gateway Timeout`

maybe we should backoff retry these?

**Comment by davidesner** [comment]
Hi, the retry policy was set up in ed456cd622fa4233b2f98dbf7d98ceea6adbc951 Any API call returning `504` is attempted 15x times before failure. In 4c060fc1c0aeb0fd3b358adfb2fa72f156800a65 I also throw UE on such failure instead of application error.
