### ISSUE TITLE
Component timed out in 3600 sec

### ISSUE THREAD

**Issue by MiroCillik** [davidesner/keboola-adform-masterdata-extractor#3]
Could you check the retry mechanism? It should return a proper error message before it times out.

**Comment by tomasfejfar** [comment]
@davidesner are you aware of this?

**Comment by yustme** [comment]
I'm putting here some more informations:
![snimek z 2019-03-04 13-06-12](https://user-images.githubusercontent.com/5272798/53732592-b7aed300-3e7e-11e9-8d44-a7a66c50419c.png)
![snimek z 2019-03-04 13-04-31](https://user-images.githubusercontent.com/5272798/53732596-b9789680-3e7e-11e9-99b4-fd8dac126434.png)

One time it has not finished and next day it finished. There was no changes in configuration between those 2 runs. So it should be some problem of connection ... and endless trying to reconnect ?

**Comment by davidesner** [comment]
Thanks for this! I am on it. It seems like incorrect setup of timeout interval.

**Comment by ondrejhlavacek** [comment]
@davidesner any update on this?
